### ISSUE TITLE
Not showing followed streams.

### ISSUE THREAD

**Issue by Jerryplayzmc** [martink635/twitchls#44] opened 2020-12-13 04:39 UTC
Usually is missing about 30% of my followed streams. Not in a particular order, just at random. Doesn't matter how many viewers they have. I miss some with 30k viewers and I miss some with 20 viewers.

**Comment by martink635** [comment] 2020-12-13 13:38
Closing this, since it's a duplicate of https://github.com/martink635/twitchls/issues/38

**Closed by martink635** 2020-12-13 13:38 UTC
